name: Webhook Trigger

on:
  push:
    branches:
      - master # 替换为你的主要分支名称

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Trigger Webhook
        run: |
          echo "hahaaha"
          echo "hahahahah1"
          echo "hahahahah2"
          echo "hahahahah4"
          echo "hahahahah4"
          curl -X GET -d 'payload=data' -H "Content-Type: application/json" http://192.168.135.159:8080/test/test1
